version: '2'
services:
  web:
    build: .
#    ports:
#      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - RABBIT_URL=amqp://guest@queue//
  queue:
    image: rabbitmq
    hostname: "rabbit_queue"
    ports:
      - "5672:5672"
  nginx:
    build: ./custom_nginx
    ports:
      - "8099:80"
  redis:
    image: redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"