version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - RABBIT_URL=amqp://guest@queue//
  queue:
    image: rabbitmq
    hostname: "rabbit_queue"
    ports:
      - "5672:5672"
  nginx:
    image: nginx
    ports:
      - "80:8099"
  redis:
    image: redis
    restart: always
    command: redis-server --appendonly yes